feat(apps/frontend-*): add internationalization to student frontend
uzh-bf/klicker-react pull request #3395
Opened 2023-02-21 13:01 UTC by sjschlapbach

This pull request adds English language support based on next-intl to the student frontend (frontend-pwa). As components in shared-components are partly also used by the lecturer frontend (frontend-manage), the corresponding library was already installed there as well.

2023-02-21 20:27 UTC, rschlaefli commented on apps/frontend-pwa/src/pages/editProfile.tsx
> +            .min(8, t('pwa.profile.passwordMinLenght', { length: '8' })),
length

2023-02-21 20:28 UTC, rschlaefli commented on apps/frontend-pwa/src/pages/editProfile.tsx
> +                .min(8, t('pwa.profile.passwordMinLenght', { length: '8' }))
length

2023-02-21 20:28 UTC, rschlaefli commented on apps/frontend-pwa/src/pages/editProfile.tsx
> +                    {Object.keys(AVATAR_OPTIONS).map((key) => (
very nice simplification

2023-02-21 20:34 UTC, rschlaefli requested changes
Need to rework the approach for getStaticProps/getServerSideProps, and remove them from components (only relevant for pages).

2023-02-21 23:49 UTC, sjschlapbach commented on apps/frontend-pwa/src/pages/editProfile.tsx
> +                    {Object.keys(AVATAR_OPTIONS).map((key) => (
thanks :)

2023-02-21 23:50 UTC, sjschlapbach commented
> Need to rework the approach for getStaticProps/getServerSideProps, and remove them from components (only relevant for pages).

Of course, this was a very non-ideal bug in the implementation... Thanks for pointing it out! Will be fixed right away.

2023-02-21 23:52 UTC, sjschlapbach commented on apps/frontend-pwa/src/pages/editProfile.tsx
> +            .min(8, t('pwa.profile.passwordMinLenght', { length: '8' })),
fixed

2023-02-21 23:52 UTC, sjschlapbach commented on apps/frontend-pwa/src/pages/editProfile.tsx
> +                .min(8, t('pwa.profile.passwordMinLenght', { length: '8' }))
fixed

2023-02-22 08:26 UTC, rschlaefli approved these changes

2023-02-22 08:50 UTC, merged