enhance(packages/graphql): ensure that group activity clue distribution is more even
uzh-bf/klicker-react pull request #3939
Opened 2023-11-09 15:35 UTC by sjschlapbach

2023-11-09 17:21 UTC, rschlaefli requested changes

2023-11-09 17:21 UTC, rschlaefli commented on packages/graphql/src/services/groups.ts
> +      const clueAssignments = group.participants.flatMap((participant) => {
refactor to use reduce instead of reassigning variables

2023-11-09 18:09 UTC, sjschlapbach commented
@rschlaefli reduce has been fixed, typing is only partially working with any[] type for the clue accumulator

2023-11-12 20:58 UTC, rschlaefli approved these changes

2023-11-12 20:59 UTC, merged